"""Models floatSession

Revision ID: 278b99c4b201
Revises: acec193e2ee3
Create Date: 2025-11-19 13:02:16.865461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '278b99c4b201'
down_revision = 'acec193e2ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.alter_column('FinalRiskLevel',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.alter_column('FinalRiskLevel',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61163557BF'))
    )
    # ### end Alembic commands ###
