"""ContactsRiskId

Revision ID: 7259bc6c5210
Revises: 
Create Date: 2025-10-09 12:18:53.354323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '7259bc6c5210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Consents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ContactId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Contacts', ['ContactId'], ['ContactId'])

    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RiskLevelId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('FinalRiskLevel', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(None, 'RiskLevels', ['RiskLevelId'], ['RiskLevelId'])
        batch_op.drop_column('RiskDetected')
        batch_op.drop_column('RiskLevel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RiskLevel', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('RiskDetected', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('FinalRiskLevel')
        batch_op.drop_column('RiskLevelId')

    with op.batch_alter_table('Consents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ContactId')

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6136D4D8A5'))
    )
    # ### end Alembic commands ###
