"""ModelsPaso

Revision ID: d909fb0e62cb
Revises: dd4110d67153
Create Date: 2025-10-22 12:55:39.630708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd909fb0e62cb'
down_revision = 'dd4110d67153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Consents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__Consents__Contac__5812160E'), type_='foreignkey')
        batch_op.drop_column('ContactId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Consents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ContactId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('FK__Consents__Contac__5812160E'), 'Contacts', ['ContactId'], ['ContactId'])

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61CE2D3EC1'))
    )
    # ### end Alembic commands ###
