"""IsDeleted

Revision ID: dd4110d67153
Revises: b5aace2965e1
Create Date: 2025-10-09 17:34:37.583927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'dd4110d67153'
down_revision = 'b5aace2965e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Consents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ContactTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('DocumentTypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('RiskLevels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsDeleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('Sessions', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('RiskLevels', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('Messages', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('DocumentTypes', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('ContactTypes', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    with op.batch_alter_table('Consents', schema=None) as batch_op:
        batch_op.drop_column('IsDeleted')

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61F9056DE2'))
    )
    # ### end Alembic commands ###
